#doctrine:
#    orm:
#        auto_generate_proxy_classes: false
#        metadata_cache_driver:
#            type: pool
#            pool: doctrine.system_cache_pool
#        query_cache_driver:
#            type: pool
#            pool: doctrine.system_cache_pool
#        result_cache_driver:
#            type: pool
#            pool: doctrine.result_cache_pool
#
#framework:
#    cache:
#        pools:
#            doctrine.result_cache_pool:
#                adapter: cache.app
#            doctrine.system_cache_pool:
#                adapter: cache.system

doctrine:
    dbal:
        default_connection:       default
        connections:
            default:
                dbname:           entmedical-db
                user:             root
                password:         9l3pAMzT9l3pAMzT
                host:             localhost
                server_version:   '5.6'
            customer:
                dbname:           entmedical
                user:             root
                password:         9l3pAMzT9l3pAMzT
                host:             localhost
                server_version:   '5.7'